

KAFKA_BOOTSTRAP_SERVER = "kafka:9092"

KAFKA_VALUE_ENCODING = "utf-8"

KAFKA_INBOUND_TOPIC = "processing_requests_executions"
KAFKA_SUCCESS_OUTBOUND_TOPIC = "successful_executions"
KAFKA_ERROR_OUTBOUND_TOPIC = "failed_executions"
KAFKA_DEAD_LETTER_QUEUE_TOPIC = "dead_letter_queue"

KAFKA_SUCCESS_ACKS = "all"
KAFKA_ERROR_ACKS = "all"
KAFKA_DEAD_LETTER_QUEUE_ACKS = "all"

KAFKA_INBOUND_GROUP_ID = "processors"
KAFKA_INBOUND_AUTO_OFFSET_RESET = "earliest"
KAFKA_INBOUND_TIMEOUT = 1000
KAFKA_INBOUND_MAX_RECORDS = 1


EXECUTION_SLEEP = 10  # 30


EXECUTION_MESSAGE_FORCE_ERROR_KEY = "force_error"
