

API_HOST = "0.0.0.0"
API_PORT = 5000


PROCESSING_REQUESTS_ENDPOINT = "/requests"
EXECUTIONS_ENDPOINT = "/requests/<request_id>/executions"
RESULTS_ENDPOINT = "/requests/<request_id>/results"


PROCESSING_REQUESTS_SERVICE_URI = "http://processing_requests:5000/requests"
PROCESSING_REQUESTS_SERVICE_SUCCESS_CODE = 201


EXECUTIONS_SERVICE_REQUEST_PARAMETER = "request_id"
EXECUTIONS_SERVICE_URI = (
    f"http://processing_requests:5000/requests/{{{EXECUTIONS_SERVICE_REQUEST_PARAMETER}}}/executions"
)
EXECUTIONS_SERVICE_CREATION_SUCCESS_CODE = 201
EXECUTIONS_SERVICE_QUERY_SUCCESS_CODE = 200
EXECUTIONS_SERVICE_QUERY_LIST_KEY = "executions"
EXECUTION_CREATION_DATE = "creation_date"

RESULTS_SERVICE_REQUEST_PARAMETER = "request_id"
RESULTS_SERVICE_URI = f"http://results_api:5000/requests/{{{EXECUTIONS_SERVICE_REQUEST_PARAMETER}}}/results"
RESULTS_SERVICE_SUCCESS_CODE = 200
RESULTS_SERVICE_RESULTS_LIST_KEY = "results"
RESULT_IS_SUCCESS_KEY = "is_success"


RESULTS_LIST_KEY = "results"


KAFKA_BOOTSTRAP_SERVER = "kafka:9092"
KAFKA_VALUE_ENCODING = "utf-8"
KAFKA_DEAD_LETTER_QUEUE_TOPIC = "dead_letter_queue"
KAFKA_DEAD_LETTER_QUEUE_ACKS = "all"


ALLOWED_FAILURES_COUNT = 3


DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S.%f"
